const STORAGE_KEY = 'lowpoly64-lang';

const objectExample = `{
  "name": "RETRO CHEST",
  "pieces": [
    {
      "name": "BODY",
      "geometry": { "type": "cube", "params": { "width": 3, "height": 2, "depth": 2 } },
      "color": "#8b5a2b",
      "position": [0, 1, 0]
    },
    {
      "name": "LID",
      "geometry": { "type": "cube", "params": { "width": 3.2, "height": 0.8, "depth": 2.2 } },
      "color": "#b87333",
      "position": [0, 2.1, 0],
      "pivot": [0, 1.8, -1],
      "parent": "BODY"
    },
    {
      "name": "LOCK",
      "geometry": { "type": "cube", "params": { "width": 0.4, "height": 0.6, "depth": 0.2 } },
      "color": "#ffcc00",
      "position": [0, 1.1, 1.1]
    }
  ]
}`;

const animationExample = `{
  "name": "open_lid",
  "duration": 1.2,
  "loop": false,
  "tracks": [
    {
      "target": "LID",
      "property": "rotation",
      "keyframes": [
        { "time": 0, "value": [0, 0, 0] },
        { "time": 1.2, "value": [-1.2, 0, 0] }
      ]
    }
  ]
}`;

const objectPrompt = `You generate importable LowPoly64 object JSON.

Return ONLY valid JSON. Do not add markdown fences. Do not add explanations.

Rules:
- Root format: { "name": string, "pieces": [...] }
- Each piece needs:
  - "name": unique string
  - "geometry": { "type": "cube" | "sphere" | "cylinder" | "cone" | "plane" | "capsule" | "torus", "params": { ... } }
  - "color": hex string like "#ffcc00"
  - "position": [x, y, z]
- Optional fields:
  - "rotation": [rx, ry, rz] in radians
  - "scale": [sx, sy, sz]
  - "pivot": [x, y, z] for the rotation origin
  - "parent": another piece name for hierarchy
- Keep piece count under 40
- Keep geometry segments modest
- Use stable piece names because animations will target those names later

Create a low-poly retro asset for LowPoly64 with this description:`;

const animationPrompt = `You generate importable LowPoly64 animation JSON.

Return ONLY valid JSON. Do not add markdown fences. Do not add explanations.

Rules:
- Format:
  {
    "name": string,
    "duration": number,
    "loop": boolean,
    "tracks": [
      {
        "target": "EXISTING_PIECE_NAME",
        "property": "position" | "rotation" | "scale" | "visible",
        "keyframes": [
          { "time": number, "value": [...] }
        ]
      }
    ]
  }
- "target" must match existing piece names exactly
- rotation values use radians [rx, ry, rz]
- position and scale use 3 numbers
- visible uses [1] or [0]
- keep duration under 10 seconds unless explicitly requested
- keep track count modest

Create a LowPoly64 animation for this object and intent:`;

const content = {
  en: {
    langButton: 'EN 🇺🇸',
    copy: 'Copy',
    copied: 'Copied',
    backToEditor: 'Back To Editor',
    heroTitle: 'Build retro low-poly assets faster',
    heroLead: 'This page explains how to use the editor, how to prepare importable JSON, and how to ask any external LLM to generate assets and animations for LowPoly64.',
    tocWorkflow: 'Basic workflow',
    tocObjectJson: 'Object JSON',
    tocAnimationJson: 'Animation JSON',
    tocPrompts: 'Ready prompts for LLMs',
    tocTips: 'Import and export tips',
    workflowTitle: 'Basic workflow',
    workflowCreateTitle: '1. Create or import',
    workflowEditTitle: '2. Edit in the viewport',
    workflowAnimateTitle: '3. Add animation when needed',
    workflowExportTitle: '4. Export your result',
    workflowCreate: [
      'Use the primitive buttons when you want to block out an asset directly in the editor.',
      'Use the template list to start from existing retro props and characters.',
      'Use "IMPORT OBJECT JSON" when you already have a JSON generated by an LLM or prepared by hand.',
    ],
    workflowEdit: [
      'Select with click. Use Ctrl+Click for multi-selection.',
      'Transform with W, E and R or by editing numeric values in the properties panel.',
      'Group parts when you want a shared root object or a parent-child hierarchy.',
    ],
    workflowAnimate: [
      'Animations are applied to a selected group, not to an isolated loose piece.',
      'Animation tracks must target exact piece names already present in the group.',
      'Use the animation import area or animation mode to test clips before exporting.',
    ],
    workflowExport: [
      'Export GLB for game-engine friendly output.',
      'Export JSON when you want to reuse the object structure later.',
      'If something is selected, the GLB export button exports the selection first.',
    ],
    objectJsonTitle: 'Object JSON',
    objectJsonLead: 'LowPoly64 imports objects as a root object with a name and a pieces array. Each piece describes one visible part of the model.',
    objectJsonNote: 'Use short, stable piece names like BODY, HEAD, ARM_L or LID. Those same names are what animation tracks will target later.',
    objectFieldsTitle: 'Important fields',
    objectFields: [
      '"name": the object name shown in the editor.',
      '"pieces": the visible parts of the object.',
      '"pivot": optional custom rotation origin for a piece.',
      '"parent": optional parent piece name when you want hierarchy.',
      '"position", "rotation" and "scale": transform values for that piece.',
    ],
    objectTypesTitle: 'Supported geometry types',
    objectTypes: ['cube', 'sphere', 'cylinder', 'cone', 'plane', 'capsule', 'torus'],
    objectExampleTitle: 'Object JSON example',
    animationJsonTitle: 'Animation JSON',
    animationJsonLead: 'Animations target piece names that already exist inside the selected group. Tracks can animate position, rotation, scale and visible.',
    animationJsonWarning: 'If target names do not match the object piece names exactly, those tracks will be skipped during import.',
    animationFieldsTitle: 'Important fields',
    animationFields: [
      '"name": the clip name shown in the editor.',
      '"duration": total length of the clip in seconds.',
      '"tracks": one or more animation tracks.',
      '"target": exact piece name already present in the object.',
      '"property": one of position, rotation, scale or visible.',
    ],
    animationFlowTitle: 'Import flow',
    animationFlow: [
      'Import or create an object first.',
      'Select the root group of that object.',
      'Paste the animation JSON in the animation import area.',
      'Play it in the timeline before exporting GLB.',
    ],
    animationExampleTitle: 'Animation JSON example',
    promptsTitle: 'Ready prompts for LLMs',
    promptsLead: 'These prompts are designed for ChatGPT, Claude, Gemini, DeepSeek, Mistral, Grok or similar tools. Paste the prompt, then add your asset description at the end.',
    projectLinkLabel: 'Project page',
    projectLinkValue: 'https://github.com/IAnMove/LowPoly64',
    objectPromptTitle: 'Object prompt',
    animationPromptTitle: 'Animation prompt',
    tipsTitle: 'Import and export tips',
    tipsImportTitle: 'Import tips',
    tipsExportTitle: 'Export tips',
    tipsImport: [
      'Keep piece names unique.',
      'Do not ask the LLM for hundreds of pieces or extremely high segments.',
      'When using hierarchy, only reference parent names that really exist.',
      'If an import fails, simplify the asset and try again.',
    ],
    tipsExport: [
      'Use JSON export when you want an editable source format for later sessions.',
      'Use GLB export when you want to move the asset into Blender, Godot or Unity.',
      'Save to local storage only as a convenience. Keep exported JSON files for real backups.',
      'Test animations inside the editor before exporting the final GLB.',
    ],
    footer: 'Keep names stable between object pieces and animation targets. If the names do not match, animation tracks will be skipped.',
  },
  es: {
    langButton: 'ES 🇪🇸',
    copy: 'Copiar',
    copied: 'Copiado',
    backToEditor: 'Volver Al Editor',
    heroTitle: 'Crea assets retro low-poly mas rapido',
    heroLead: 'Esta pagina explica como usar el editor, como preparar JSON importables y como pedir a un LLM externo que genere objetos y animaciones para LowPoly64.',
    tocWorkflow: 'Flujo basico',
    tocObjectJson: 'JSON de objetos',
    tocAnimationJson: 'JSON de animaciones',
    tocPrompts: 'Prompts listos para LLMs',
    tocTips: 'Consejos de importacion y exportacion',
    workflowTitle: 'Flujo basico',
    workflowCreateTitle: '1. Crear o importar',
    workflowEditTitle: '2. Editar en el viewport',
    workflowAnimateTitle: '3. Anadir animacion cuando haga falta',
    workflowExportTitle: '4. Exportar el resultado',
    workflowCreate: [
      'Usa las primitivas cuando quieras bloquear un asset directamente en el editor.',
      'Usa la lista de plantillas para empezar desde props y personajes retro ya preparados.',
      'Usa "IMPORT OBJECT JSON" cuando ya tengas un JSON generado por un LLM o escrito a mano.',
    ],
    workflowEdit: [
      'Selecciona con click. Usa Ctrl+Click para multi-seleccion.',
      'Transforma con W, E y R o editando los valores numericos del panel de propiedades.',
      'Agrupa piezas cuando quieras un objeto raiz compartido o una jerarquia padre-hijo.',
    ],
    workflowAnimate: [
      'Las animaciones se aplican a un grupo seleccionado, no a una pieza suelta.',
      'Los tracks deben apuntar a nombres de pieza exactos que ya existan dentro del grupo.',
      'Usa el area de importacion de animacion o el animation mode para probar clips antes de exportar.',
    ],
    workflowExport: [
      'Exporta GLB para sacar un archivo listo para motores de juego.',
      'Exporta JSON cuando quieras reutilizar despues la estructura del objeto.',
      'Si hay algo seleccionado, el boton GLB exporta primero la seleccion.',
    ],
    objectJsonTitle: 'JSON de objetos',
    objectJsonLead: 'LowPoly64 importa objetos como un objeto raiz con nombre y un array pieces. Cada pieza describe una parte visible del modelo.',
    objectJsonNote: 'Usa nombres de pieza cortos y estables como BODY, HEAD, ARM_L o LID. Esos mismos nombres son los que usaran luego los tracks de animacion.',
    objectFieldsTitle: 'Campos importantes',
    objectFields: [
      '"name": nombre del objeto mostrado en el editor.',
      '"pieces": partes visibles del objeto.',
      '"pivot": origen de rotacion opcional para una pieza.',
      '"parent": nombre opcional de otra pieza para crear jerarquia.',
      '"position", "rotation" y "scale": transformaciones de esa pieza.',
    ],
    objectTypesTitle: 'Tipos de geometria soportados',
    objectTypes: ['cube', 'sphere', 'cylinder', 'cone', 'plane', 'capsule', 'torus'],
    objectExampleTitle: 'Ejemplo de JSON de objeto',
    animationJsonTitle: 'JSON de animaciones',
    animationJsonLead: 'Las animaciones apuntan a nombres de pieza que ya existen dentro del grupo seleccionado. Los tracks pueden animar position, rotation, scale y visible.',
    animationJsonWarning: 'Si los nombres target no coinciden exactamente con los nombres de pieza del objeto, esos tracks se ignoraran durante la importacion.',
    animationFieldsTitle: 'Campos importantes',
    animationFields: [
      '"name": nombre del clip mostrado en el editor.',
      '"duration": duracion total del clip en segundos.',
      '"tracks": uno o varios tracks de animacion.',
      '"target": nombre exacto de una pieza ya presente en el objeto.',
      '"property": uno de position, rotation, scale o visible.',
    ],
    animationFlowTitle: 'Flujo de importacion',
    animationFlow: [
      'Importa o crea primero un objeto.',
      'Selecciona el grupo raiz de ese objeto.',
      'Pega el JSON de animacion en el area de importacion de animacion.',
      'Reprodúcelo en la timeline antes de exportar GLB.',
    ],
    animationExampleTitle: 'Ejemplo de JSON de animacion',
    promptsTitle: 'Prompts listos para LLMs',
    promptsLead: 'Estos prompts estan pensados para ChatGPT, Claude, Gemini, DeepSeek, Mistral, Grok o herramientas parecidas. Pega el prompt y despues anade tu descripcion al final.',
    projectLinkLabel: 'Pagina del proyecto',
    projectLinkValue: 'https://github.com/IAnMove/LowPoly64',
    objectPromptTitle: 'Prompt de objeto',
    animationPromptTitle: 'Prompt de animacion',
    tipsTitle: 'Consejos de importacion y exportacion',
    tipsImportTitle: 'Consejos para importar',
    tipsExportTitle: 'Consejos para exportar',
    tipsImport: [
      'Mantén los nombres de pieza unicos.',
      'No le pidas al LLM cientos de piezas ni segmentos exagerados.',
      'Si usas jerarquia, referencia solo nombres de padre que realmente existan.',
      'Si una importacion falla, simplifica el asset y vuelve a intentarlo.',
    ],
    tipsExport: [
      'Usa export JSON cuando quieras un formato fuente editable para sesiones futuras.',
      'Usa export GLB cuando quieras mover el asset a Blender, Godot o Unity.',
      'Guarda en local storage solo como comodidad. Para backups reales, exporta JSON.',
      'Prueba las animaciones dentro del editor antes de exportar el GLB final.',
    ],
    footer: 'Mantén estables los nombres entre piezas del objeto y targets de animacion. Si no coinciden, esos tracks se ignoraran.',
  },
};

function getLang() {
  return localStorage.getItem(STORAGE_KEY) || 'en';
}

function setLang(lang) {
  localStorage.setItem(STORAGE_KEY, lang);
}

function fillList(id, items) {
  const list = document.getElementById(id);
  if (!list) return;
  list.replaceChildren(...items.map((item) => {
    const li = document.createElement('li');
    li.textContent = item;
    return li;
  }));
}

function fillPills(id, items) {
  const container = document.getElementById(id);
  if (!container) return;
  container.replaceChildren(...items.map((item) => {
    const pill = document.createElement('span');
    pill.className = 'pill';
    pill.textContent = item;
    return pill;
  }));
}

function render(lang) {
  const copyLabel = content[lang].copy;

  document.documentElement.lang = lang;
  document.querySelectorAll('[data-help]').forEach((el) => {
    const key = el.getAttribute('data-help');
    if (content[lang][key]) {
      el.textContent = content[lang][key];
    }
  });

  fillList('workflow-create-list', content[lang].workflowCreate);
  fillList('workflow-edit-list', content[lang].workflowEdit);
  fillList('workflow-animate-list', content[lang].workflowAnimate);
  fillList('workflow-export-list', content[lang].workflowExport);
  fillList('object-fields-list', content[lang].objectFields);
  fillList('animation-fields-list', content[lang].animationFields);
  fillList('animation-flow-list', content[lang].animationFlow);
  fillList('tips-import-list', content[lang].tipsImport);
  fillList('tips-export-list', content[lang].tipsExport);
  fillPills('object-types-pills', content[lang].objectTypes);

  document.getElementById('object-json-example').textContent = objectExample;
  document.getElementById('animation-json-example').textContent = animationExample;
  document.getElementById('object-prompt').textContent = objectPrompt;
  document.getElementById('animation-prompt').textContent = animationPrompt;
  const projectLink = document.getElementById('project-link');
  if (projectLink) {
    projectLink.textContent = `${content[lang].projectLinkLabel}: ${content[lang].projectLinkValue}`;
    projectLink.href = content[lang].projectLinkValue;
  }

  document.getElementById('help-lang-toggle').textContent = content[lang].langButton;
  document.querySelectorAll('[data-copy-target]').forEach((button) => {
    button.textContent = copyLabel;
  });
}

function wireCopyButtons() {
  document.querySelectorAll('[data-copy-target]').forEach((button) => {
    button.addEventListener('click', async () => {
      const targetId = button.getAttribute('data-copy-target');
      const target = document.getElementById(targetId);
      if (!target) return;

      const original = content[getLang()].copy;
      try {
        await navigator.clipboard.writeText(target.textContent);
        button.textContent = content[getLang()].copied;
        setTimeout(() => {
          button.textContent = original;
        }, 1200);
      } catch {
        window.prompt('Copy this text:', target.textContent);
      }
    });
  });
}

document.addEventListener('DOMContentLoaded', () => {
  render(getLang());
  wireCopyButtons();

  document.getElementById('help-lang-toggle')?.addEventListener('click', () => {
    const next = getLang() === 'en' ? 'es' : 'en';
    setLang(next);
    render(next);
  });
});
